#!/usr/bin/env python3
"""Regenerate ``connectors/tool_schema_fingerprints.json`` from the live tool surface.

Connects an in-process FastMCP client to a plain server carrying this
package's nine tools (no auth/network/fleet-registration wiring — those are
concerns of ``agent_connector_sdk.mcp.server.create_mcp_server``, irrelevant
to a tool's client-visible schema) and fingerprints exactly what a real
client's ``tools/list`` would see, via
``agent_connector_sdk.certify.fingerprints.tool_fingerprint`` — the same
function ``discover()`` verifies against at extraction time.

Run after changing any tool's signature or docstring-derived schema:

    uv run --frozen python scripts/compute_tool_fingerprints.py --apply
"""

from __future__ import annotations

import argparse
import asyncio
import json
from pathlib import Path

from agent_connector_sdk.certify.fingerprints import tool_fingerprint
from fastmcp import Client, FastMCP

from world_reference_mcp.mcp.clients import Clients
from world_reference_mcp.mcp.tools_nutrition import register_nutrition_tools
from world_reference_mcp.mcp.tools_observations import register_observation_tools
from world_reference_mcp.mcp.tools_taxonomy import register_taxonomy_tools
from world_reference_mcp.mcp.tools_terms import register_term_tools
from world_reference_mcp.mcp.tools_wikidata import register_wikidata_tools

_OUTPUT = Path(__file__).resolve().parent.parent / (
    "world_reference_mcp/connectors/tool_schema_fingerprints.json"
)


def _bare_server() -> FastMCP:
    mcp: FastMCP = FastMCP("world-reference-mcp")
    clients = Clients()
    register_taxonomy_tools(mcp, clients)
    register_term_tools(mcp, clients)
    register_nutrition_tools(mcp, clients)
    register_observation_tools(mcp, clients)
    register_wikidata_tools(mcp, clients)
    return mcp


async def _fingerprints() -> dict[str, str]:
    mcp = _bare_server()
    async with Client(mcp) as client:
        tools = await client.list_tools()
    return {tool.name: tool_fingerprint(tool) for tool in tools}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true", help="write the output file")
    args = parser.parse_args()
    fingerprints = asyncio.run(_fingerprints())
    document = {
        "_comment": (
            "Generated by scripts/compute_tool_fingerprints.py from the live "
            "tools/list schema. Never hand-edit."
        ),
        "tools": dict(sorted(fingerprints.items())),
    }
    text = json.dumps(document, indent=2, sort_keys=False) + "\n"
    if args.apply:
        _OUTPUT.write_text(text)
        print(f"wrote {_OUTPUT}")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
